"""把解析好的 Schema 生成为一个可独立 import 的 .py 文件。

生成的文件只依赖 minipb.runtime，不需要原始 .mpb 文件。
"""

from .schema import BUILTIN_TYPES

_HEADER = """\
# Generated by minipb from {source}. DO NOT EDIT.
from minipb.runtime import Field, Message

"""


def generate(schema, source_name="schema.mpb"):
    """返回生成的 Python 源码字符串。"""
    chunks = [_HEADER.format(source=source_name)]
    for msg in schema.messages:
        lines = ["class %s(Message):" % msg.name, "    _fields = ["]
        for f in msg.fields:
            if f.type in BUILTIN_TYPES:
                args = '%r, %d, %r, %r' % (f.name, f.number, f.type, f.label)
            else:
                args = '%r, %d, %r, %r, msg_type=%r' % (
                    f.name, f.number, "message", f.label, f.type,
                )
            lines.append("        Field(%s)," % args)
        lines.append("    ]")
        lines.append("")
        chunks.append("\n".join(lines))
    # 所有类定义完之后，把 msg_type 字符串解析成真正的类（支持前向引用）
    chunks.append("")
    for msg in schema.messages:
        chunks.append("%s._resolve(globals())" % msg.name)
    return "\n".join(chunks) + "\n"
