"""代码生成器：把 Schema 编译成一个可独立 import 的 .py 文件。

选择「生成 .py 文件」而不是运行时动态构造，理由见 README。
生成的文件只依赖 minipb.runtime，内容是人类可读的 Field 声明列表。
"""

from .runtime import SCALAR_TYPES

_HEADER = '''\
"""Generated by minipb. DO NOT EDIT.

source schema: {source}
"""

from minipb.runtime import Field, Message

'''


def compile_schema(schema, source="<schema>"):
    """把 Schema 对象编译成 Python 源码字符串。"""
    out = [_HEADER.format(source=source)]
    for msg in schema.messages:
        out.append("class %s(Message):\n" % msg.name)
        out.append("    _fields_ = [\n")
        for f in msg.fields:
            out.append("        Field(%r, %r, %r, %d),\n"
                       % (f.name, f.type_name, f.label, f.number))
        out.append("    ]\n\n\n")
    return "".join(out)
