"""Generated by minipb. DO NOT EDIT.

source schema: examples/person.mpb
"""

from minipb.runtime import Field, Message

class Person(Message):
    _fields_ = [
        Field('name', 'string', 'required', 1),
        Field('age', 'int32', 'optional', 2),
        Field('emails', 'string', 'repeated', 3),
        Field('addr', 'Address', 'optional', 4),
    ]


class Address(Message):
    _fields_ = [
        Field('city', 'string', 'required', 1),
        Field('zip', 'int32', 'optional', 2),
    ]


